# This class reads the keyvault to get particular secret/s.
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "7cc33e59-c621-4257-a15d-49720ba0e045"
    keyvaultName: "jaydemo-kv-v2"
    tenantId: "4c475f22-5bbf-43c6-833d-810e9335ade4" # Keep this if it's your true corporate Tenant ID, or change to match your subscription directory
    objects: |
      array:
        - |
          objectName: mysecret
          objectType: secret
          objectVersion: ""