# This class reads the keyvault to get particular secret/s.
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
#    userAssignedIdentityID:  "/subscriptions/eac7dbb7-a7ec-45bc-98de-902b34a2f404/resourcegroups/MC_jaydemo-rg_jaydemo-aks_australiaeast/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azurekeyvaultsecretsprovider-jaydemo-aks"
    userAssignedIdentityID: "2c6d4b30-5cbc-420f-8f93-dc8df1253b8b"
    keyvaultName: "jaydemo-kv-v2"
    tenantId: "4c475f22-5bbf-43c6-833d-810e9335ade4" # Keep this if it's your true corporate Tenant ID, or change to match your subscription directory
    objects: |
      array:
        - |
          objectName: mysecret
          objectType: secret
          objectVersion: ""